# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo hello
          name: echo Hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo world
  print_project-author:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: "echo an env var with the name of the project author"
          command: |
            echo $PROJECT_AUTHOR


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_project-author:
          requires: [print_world]
